### ISSUE TITLE
Nonlinear optimisation

### ISSUE THREAD

**Issue by patrickocal** [NCKempke/PIPS-IPMpp#1]
Hi folks,

I've enjoyed reading your recent (2022) paper in EJOR. This looks like exciting work. I'm also interested in your application to energy/climate change: though more from an economics perspective. This brings me to the question:

Is there any hope of supporting nonlinear optimisation problems (in the near future)?

"PIPS-IPM++ is a (MPI + OpenMP) parallel interior-point method for doubly bordered block diagonal Linear Programs (QPs with linear constraints are currently not supported - we could do that if wished for)."

Thanks,
Patrick

**Comment by NCKempke** [comment]
Hi Patrick,

sadly, I have to say no to that. There might be hope for QPs with linear constraints, as this should not be too difficult to re-introduce, but only if we can get our hands on actual problems exhibiting the PIPS-IPMpp required structure.

Generally, there will never be a full NLP (or even LP) support for that matter. The special algorithm of PIPS will always also have special structure requirements on the problems. I am not sure what exactly you question was aiming at, I hope this answers it though.

Cheers,
Nils

**Comment by patrickocal** [comment]
Yes, the special structure requirements are satisfied in the stochastic problems I generally work with.

Thanks for your answer. 

Would you say that the best ways to go (if I wanted access to something like what you have built) are the following
1. PIPS-NLP - parallel MPI interior-point for structured NLPs
2. PETSc itself

Is PIPS still being maintained? (Last update is over 2 years ago.)

Cheers,
Patrick

**Comment by NCKempke** [comment]
I see - so PIPS-NLP might do the trick here but sadly I am not sure of its state/interfaces. But in this case, maybe Cosmin Petra can answer you questions here - he would also know best about the general maintenance of PIPS-NLP. 
I would recommend asking the Argonne people directly :)

Since I am not too familiar with the you problem, the PIPS-NLP interface and the PETSc, I sadly cannot tell you what would work best. For sure you could make both work somehow but the effort might differ significantly. But probably the maintainers of the other packages are more than happy to help you here :)

Cheers,
Nils

**Comment by patrickocal** [comment]
Thanks Nils, that makes sense. I’ll try to get in touch with Cosmin Petra
and folks at the ANL.

Cheers,
Patrick
